### ISSUE TITLE
Data acquisition should use same logging strategy as data management

### ISSUE THREAD

**Issue by rsnape** [IESD/MECS#2]
At the moment, we're printing out to console for debugging / logging.  We could handle all this via a Logger - probably the one set up in the conf script.

**Comment by ggstuart** [comment]
I've refactored the top-level data acquisition code into a class MECSBoard. This has logging configured properly so its easy to add log statements using 

```
log.debug(f"value = {value}")
log.info("Normal things are happening")
log.warning("An issue has been detected")
log.error("An error has occurred")
```

There is an example [here](https://github.com/IESD/MECS/blob/01241668495e96d4212d789c19b1d1b0c53b2913/MECS/data_acquisition/__init__.py#L36).

This allows us to configure the prototype system to log at `debug` level so we can see what's going on in detail. When we deploy to the wild, we can configure the systems to log at `info` or `warning` level and ignore the boring information.

We should think about what we want in the log file of a unit in the field. The log file should contain a register of what was happening but a huge log file listing every reading is not so useful.

**Comment by rsnape** [comment]
Hi Graeme,

Getting out from under the marking.  Some nice improvements you have made over the past few days.  There’s a couple of bits we need to tidy up on the config – I see you’ve looked at the info on the ADCPi config (effective range and so on), but there’s also sensor peripheral config (for the midpoint and mVperAmp).  We need to have a chat shortly – the dev on the board in the lab has diverged a bit and I need to do some nice merging.

The config and calibration strategy is what I mainly want to talk about so here is what I’m wrestling with for you to muse on:

We (probably( need to account for variation between different physical instances of the same type of sensor. Should the calibration file contain default values for each sensor type as well as the facility to have per-channel calibration constants added, or should we hand calibrate each box at manufacture and hard code the calibration constants in per-channel?

I tend to the former as it *should* be easier to swap out a sensor and re-calibrate.  However, I’m running at flat-out and would appreciate a sense check of the use cases.

All the best,

Richard

**Comment by ggstuart** [comment]
How about we hard-code the default values into the code and let the calibration files override those?

Something like [this](https://github.com/IESD/MECS/blob/01241668495e96d4212d789c19b1d1b0c53b2913/MECS/data_acquisition/__init__.py#L63) where the "fallback" keyword argument sets the default value if no value is found in the configuration file.
