### ISSUE TITLE
Consider replacing the copied gist for aqi.py with this `sds011` library

### ISSUE THREAD

**Issue by rsnape** [IESD/MECS#3]
This is an installable package to support the SDS011 particulate sensor.  **_Might_** be more complete/supported, but perhaps not.

https://pypi.org/project/sds011/

**Comment by ggstuart** [comment]
Is this possible now? It would be great to remove the code and simply add it as a dependency.

**Comment by rsnape** [comment]
Becoming redundant due to switch of particulate sensor hardware I think
